version: '2'
services:
    bookyourmovie-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/BookYourMovie/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=BookYourMovie
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
